apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-data
  namespace: valheim
  labels:
    app: valheim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
